package com.ryanwemmer.options.gui;

import javax.swing.GroupLayout;
import javax.swing.JFrame;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JSeparator;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.WindowConstants;

public class StartGuix extends JFrame {

	/**
	 * Creates new form StartGui
	 */
	public StartGuix() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jSeparator1 = new JSeparator();
        jMenuBar2 = new JMenuBar();
        jMenu10 = new JMenu();
        jMenu11 = new JMenu();
        jMenuBar1 = new JMenuBar();
        jMenu2 = new JMenu();
        jMenuItemImportProducts = new JMenuItem();
        jMenuViewProducts = new JMenu();
        jMenuItemViewProductsByVendor = new JMenuItem();
        jMenuItemViewProductsBySku = new JMenuItem();
        jMenuItemUpdateProducts = new JMenuItem();
        jMenuItemExportProducts = new JMenuItem();
        jMenuDeleteProducts = new JMenu();
        jMenuItemDeleteProductsByVendor = new JMenuItem();
        jMenuItemDeleteProductsBySku = new JMenuItem();
        jMenu1 = new JMenu();
        jMenuAttributes = new JMenu();
        jMenuItemNewAttributes = new JMenuItem();
        jMenuItemChangeAttributes = new JMenuItem();
        jMenuItemAttributeExportOrder = new JMenuItem();
        jMenuCategories = new JMenu();
        jMenuItemGetCategories = new JMenuItem();
        jMenuMySQL = new JMenu();
        jMenuItemTestMySQLConnection = new JMenuItem();
        jMenuItemSetupMySQL = new JMenuItem();
        jMenuItemCreateSetupFile = new JMenuItem();
        jMenuShipping = new JMenu();
        jMenuItemShippingComingSoon = new JMenuItem();
        jMenuSuppliers = new JMenu();
        jMenuItemCreateSupplier = new JMenuItem();
        jMenuItemEditSupplierInformation = new JMenuItem();

        jMenu10.setText("File");
        jMenuBar2.add(jMenu10);

        jMenu11.setText("Edit");
        jMenuBar2.add(jMenu11);

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        jMenu2.setText("Products");

        jMenuItemImportProducts.setText("Import Products");
        jMenu2.add(jMenuItemImportProducts);

        jMenuViewProducts.setText("View Product(s)");

        jMenuItemViewProductsByVendor.setText("By Vendor");
        jMenuItemViewProductsByVendor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemViewProductsByVendorActionPerformed(evt);
            }
        });
        jMenuViewProducts.add(jMenuItemViewProductsByVendor);

        jMenuItemViewProductsBySku.setText("By SKU");
        jMenuViewProducts.add(jMenuItemViewProductsBySku);

        jMenu2.add(jMenuViewProducts);

        jMenuItemUpdateProducts.setText("Update Products");
        jMenu2.add(jMenuItemUpdateProducts);

        jMenuItemExportProducts.setText("Export Products");
        jMenu2.add(jMenuItemExportProducts);

        jMenuDeleteProducts.setText("Delete Products");

        jMenuItemDeleteProductsByVendor.setText("By Vendor");
        jMenuDeleteProducts.add(jMenuItemDeleteProductsByVendor);

        jMenuItemDeleteProductsBySku.setText("By SKU");
        jMenuDeleteProducts.add(jMenuItemDeleteProductsBySku);

        jMenu2.add(jMenuDeleteProducts);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("Settings");

        jMenuAttributes.setText("Attributes");

        jMenuItemNewAttributes.setText("New Attribute");
        jMenuItemNewAttributes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNewAttributesActionPerformed(evt);
            }
        });
        jMenuAttributes.add(jMenuItemNewAttributes);

        jMenuItemChangeAttributes.setText("Change Attribute Properties");
        jMenuItemChangeAttributes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemChangeAttributesActionPerformed(evt);
            }
        });
        jMenuAttributes.add(jMenuItemChangeAttributes);

        jMenuItemAttributeExportOrder.setText("Edit Export Order");
        jMenuAttributes.add(jMenuItemAttributeExportOrder);

        jMenu1.add(jMenuAttributes);

        jMenuCategories.setText("Categories");

        jMenuItemGetCategories.setText("Get Categories");
        jMenuCategories.add(jMenuItemGetCategories);

        jMenu1.add(jMenuCategories);

        jMenuMySQL.setText("MySQL");

        jMenuItemTestMySQLConnection.setText("Test MySQL Connection");
        jMenuMySQL.add(jMenuItemTestMySQLConnection);

        jMenuItemSetupMySQL.setText("Setup MySQL");
        jMenuItemSetupMySQL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSetupMySQLActionPerformed(evt);
            }
        });
        jMenuMySQL.add(jMenuItemSetupMySQL);

        jMenuItemCreateSetupFile.setText("Create Setup File (Advanced!)");
        jMenuMySQL.add(jMenuItemCreateSetupFile);

        jMenu1.add(jMenuMySQL);

        jMenuShipping.setText("Shipping");

        jMenuItemShippingComingSoon.setText("Coming soon...");
        jMenuShipping.add(jMenuItemShippingComingSoon);

        jMenu1.add(jMenuShipping);

        jMenuSuppliers.setText("Suppliers");

        jMenuItemCreateSupplier.setText("Create Supplier");
        jMenuItemCreateSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCreateSupplierActionPerformed(evt);
            }
        });
        jMenuSuppliers.add(jMenuItemCreateSupplier);

        jMenuItemEditSupplierInformation.setText("Edit Supplier Information");
        jMenuSuppliers.add(jMenuItemEditSupplierInformation);

        jMenu1.add(jMenuSuppliers);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 202, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 228, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void jMenuItemSetupMySQLActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        // TODO add your handling code here:
    }                                                   

    private void jMenuItemNewAttributesActionPerformed(java.awt.event.ActionEvent evt) {                                                       
        // TODO add your handling code here:
    }                                                      

    private void jMenuItemChangeAttributesActionPerformed(java.awt.event.ActionEvent evt) {                                                          
        // TODO add your handling code here:
    }                                                         

    private void jMenuItemViewProductsByVendorActionPerformed(java.awt.event.ActionEvent evt) {                                                              
        // TODO add your handling code here:
    }                                                             

    private void jMenuItemCreateSupplierActionPerformed(java.awt.event.ActionEvent evt) {                                                        
        // TODO add your handling code here:
    }                                                       

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(StartGuix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(StartGuix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(StartGuix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(StartGuix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new StartGuix().setVisible(true);
			}
		});
	}
    // Variables declaration - do not modify                     
    private JMenu jMenu1;
    private JMenu jMenu10;
    private JMenu jMenu11;
    private JMenu jMenu2;
    private JMenu jMenuAttributes;
    private JMenuBar jMenuBar1;
    private JMenuBar jMenuBar2;
    private JMenu jMenuCategories;
    private JMenu jMenuDeleteProducts;
    private JMenuItem jMenuItemAttributeExportOrder;
    private JMenuItem jMenuItemChangeAttributes;
    private JMenuItem jMenuItemCreateSetupFile;
    private JMenuItem jMenuItemCreateSupplier;
    private JMenuItem jMenuItemDeleteProductsBySku;
    private JMenuItem jMenuItemDeleteProductsByVendor;
    private JMenuItem jMenuItemEditSupplierInformation;
    private JMenuItem jMenuItemExportProducts;
    private JMenuItem jMenuItemGetCategories;
    private JMenuItem jMenuItemImportProducts;
    private JMenuItem jMenuItemNewAttributes;
    private JMenuItem jMenuItemSetupMySQL;
    private JMenuItem jMenuItemShippingComingSoon;
    private JMenuItem jMenuItemTestMySQLConnection;
    private JMenuItem jMenuItemUpdateProducts;
    private JMenuItem jMenuItemViewProductsBySku;
    private JMenuItem jMenuItemViewProductsByVendor;
    private JMenu jMenuMySQL;
    private JMenu jMenuShipping;
    private JMenu jMenuSuppliers;
    private JMenu jMenuViewProducts;
    private JSeparator jSeparator1;
    // End of variables declaration                   
}
